### ISSUE TITLE
Process CSV data file and generate a new CSV file

### ISSUE THREAD

**Issue by thariyarox** [thariyarox/hacktoberfest-CoinSpot-Data-Crawler#10]
In [1], sample CSV data file is there. A python program must be written (process_data.py) to read the data/test_data.csv file and create a new file (processed_data.csv) in the data folder. 

Instructions are as following.

1. Each data row has following columns where the values are separated by commas. If a value of any column in (buy, sell, market_cap, volume, change) is empty for any column, set it as 0 in the processed_data.csv file. The code_name and name columns will not be empty at any point.
code_name | name | buy | sell | market_cap | volume | change

2. The (buy, sell, market_cap, volume) column values start with $ sign. Remove the $ sign. The values may contain commas. Remove the commas. The values may be wrapped in double quotes. Remove the double quotes. If the value ends with 'B', multiply the value by 1 Billion and give the numeric value. If the value ends with 'M', multiply the value by 1 Million and give the numeric value.

[1] https://github.com/thariyarox/CoinSpot-Data-Crawler/blob/master/data/test_data.csv

**Comment by DriftingShadows** [comment]
Do I have to be assigned to give this a go?

**Comment by thariyarox** [comment]
@DriftingShadows I assigned the task to you. You can start the work on it now ! Thanks !

**Comment by shreyabaid007** [comment]
I'll be glad to take this up

**Comment by thariyarox** [comment]
Hi @shreyabaid007, I assigned this issue to @DriftingShadows . However, there are some more similar tasks we need to get done. I will create new a new issue for that and let you know today. Thanks a lot for your support.

**Comment by thariyarox** [comment]
@shreyabaid007 - I created a new issue https://github.com/thariyarox/CoinSpot-Data-Crawler/issues/13 . Would you be able to take it ?
