### ISSUE TITLE
Process a CSV file and do calculations on the available data using Python

### ISSUE THREAD

**Issue by thariyarox** [thariyarox/hacktoberfest-CoinSpot-Data-Crawler#13]
In [1], you can find the processed_data.csv file which has following columns separated by comma.

code_name | name | buy | sell | market_cap | volume | change

Your task is to write a python program to read all the entries and generate a new CSV file (stats.csv) in the same folder. You need to introduce two new columns (difference and bid_percentage).

difference = buy - sell 

bid_percentage = ( (buy - sell) / sell ) * 100

Then you need to sort all the records in ascending order from the bid_percentage column value and generate the stats.csv file.

[1] https://github.com/thariyarox/CoinSpot-Data-Crawler/blob/master/data/processed_data.csv

**Comment by kartavyashankar** [comment]
@thariyarox 
I am ready for this, please assign me this issue.

**Comment by thariyarox** [comment]
Hi @kartavyashankar - Great ! I just assigned it to you.

**Comment by quangxbt** [comment]
@thariyarox plz assign me this issue. thank you very much

**Comment by kartavyashankar** [comment]
@thariyarox 
I have coded it, now please tell me where do I put my python program in your project?

**Comment by thariyarox** [comment]
@kartavyashankar - I added a new 'processors' folder. Put the python program there.

**Comment by kartavyashankar** [comment]
Thank you

**Comment by kartavyashankar** [comment]
@thariyarox 
I have opened a pull request, see to it please :)

**Comment by thariyarox** [comment]
@kartavyashankar - Thanks a lot for your contribution !!!
