### ISSUE TITLE
Modify the run.py to run a series of python commands together

### ISSUE THREAD

**Issue by thariyarox** [thariyarox/hacktoberfest-CoinSpot-Data-Crawler#16]
You need to modify the crawler/run.py program to run the following tasks.

1. Currently it runs the 'scrapy crawl coinspot -o test_data.csv' command.
2. Modify it so that the test_data.csv file is generated in the data folder.
3. After that, run the processors/process_data.py script. This will process the test_data.csv file and generate processed_data.csv file in the data folder.
4. After that, run the processors/process_csv.py script. This will process the processed_data.csv file and generate stats.csv file. 

All above steps should be done in order by modifying the run.py program.

**Comment by cskinner74** [comment]
Hey there! I'd be willing to work on this. To clarify on 4, I'm assuming the output for the csv should also go to the data folder?

**Comment by thariyarox** [comment]
@wskinner74 yes correct. All the CSV files should be generated in the data folder. That is already completed by the existing scripts in the processors folder.

What you need to do is to run the given python programs in the given order from the crawler/run.py

**Comment by thariyarox** [comment]
@wskinner74 yes correct. All the CSV files should be generated in the data folder. That is already completed by the existing scripts in the processors folder.

What you need to do is to run the given python programs in the given order from the crawler/run.py

**Comment by cskinner74** [comment]
@thariyarox perfect, thanks!

**Comment by cskinner74** [comment]
I think I've got it, however when it gets to the process_csv script, it generates an error:
`TypeError: unsupported operand type(s) for -: 'str' and 'str'` at Line 4 of process_csv.py

**Comment by thariyarox** [comment]
@wskinner74 - I can individually run the process_csv script without any error. Can you check if it individually runs for you?

**Comment by cskinner74** [comment]
@thariyarox I checked manually and I'm getting the same thing. It may be an issue with my local environment. I'm gonna send the PR so you can take a look and see if I missed anything, and also make sure my update to run.py runs on your end.

**Comment by thariyarox** [comment]
@wskinner74 Thanks for the contribution. Once the other issue is resolved, I will merge your PR and close this issue.

**Comment by thariyarox** [comment]
@wskinner74 Thanks for the contribution. Once the other issue is resolved, I will merge your PR and close this issue.

**Comment by thariyarox** [comment]
@wskinner74 Thanks for the contribution. Once the other issue is resolved, I will merge your PR and close this issue.

**Comment by thariyarox** [comment]
I am closing this issue as it is fixed with PR https://github.com/thariyarox/CoinSpot-Data-Crawler/pull/19
