### ISSUE TITLE
Develop a Python Data Crawler for for extracting data from CoinSpot crypto currency trading platform

### ISSUE THREAD

**Issue by thariyarox** [thariyarox/hacktoberfest-CoinSpot-Data-Crawler#3]
Follow the instructions in the readme file of this project to know more about the project requrirements.

**Comment by djeni98** [comment]
Hey, I have experience with scrapy, so it seems a good issue for me. Since it is a single page, I can try another approach.

**Comment by thariyarox** [comment]
Yes, go ahead with scrapy and send a PR !

**Comment by djeni98** [comment]
Ok, I will use scrapy then. You can assign this issue to me.

**Comment by djeni98** [comment]
Hacktoberfest rules are changing (see PR digitalocean/hacktoberfest#596). Could you add "hacktoberfest" tag to your repository?

If you don't add it, your repo will not be participating in Hacktoberfest. 

(I picked this screenshot from my profile page in hacktoberfest profile site)
![image](https://user-images.githubusercontent.com/25268297/95004081-dfb36a80-05bc-11eb-8c86-494da2cdd8f0.png)

**Comment by thariyarox** [comment]
I renamed the repository name to start with 'hacktoberfest-'. Reviewed your PR and merged it after labeling as 'hacktoberfest-accepted'.

**Comment by thariyarox** [comment]
Feel free to change the readme with the instructions for running the scripts.

**Comment by thariyarox** [comment]
@djeni98 I tested the code and it's perfectly working !! Thanks a lot for your contribution. I opened a new issue to write the crawled data into a text file. https://github.com/thariyarox/CoinSpot-Data-Crawler/issues/6 
It's great if you can work on that too !

**Comment by thariyarox** [comment]
@djeni98 It seems somebody else is also interested, so I assigned the new issue to him. There will be few more improvements to be done afterwards. I will keep you posted. Thanks !
