### ISSUE TITLE
Write the crawled data into a text file

### ISSUE THREAD

**Issue by thariyarox** [thariyarox/hacktoberfest-CoinSpot-Data-Crawler#6]
Create a text file in the current directory and write the extracted data from the crawler into the file

**Comment by codescientist703** [comment]
Hi, Can i work on this issue ? Should the data be stored in the form of a dictionary in the text file ?

**Comment by thariyarox** [comment]
@codescientist703 Sure, go ahead. In the text file, store each record in a separate line. You can store them as key value pairs like below. I will assign the issue to you

key1:value1, key2:value2, key3:value3 .....

**Comment by codescientist703** [comment]
Hi, can you review this PR  #7  ?.  I have made a new pipeline that will add the data to the text file in the format you specified.
