### ISSUE TITLE
Create a python script to run the crawler and save the crawled data in CSV file

### ISSUE THREAD

**Issue by thariyarox** [thariyarox/hacktoberfest-CoinSpot-Data-Crawler#8]
Currently there are few manual steps required to run the crawler and store the data in a CSV file. We need a single main program (eg: run.py) where the user can simply run that script which downloads the data as a CSV file automatically.

**Comment by codescientist703** [comment]
Hi, Can you assign it to me? Thanks!

**Comment by codescientist703** [comment]
Hi, here is PR #9

**Comment by thariyarox** [comment]
Thanks @codescientist703 for sending the PR !
